{{- if (.Values.serviceAccount).create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "arc-cleaner.fullname" . }}
  namespace: {{ tpl .Values.config.namespace . }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "delete"]
- apiGroups: ["actions.github.com"]
  resources: ["ephemeralrunners"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "arc-cleaner.fullname" . }}
  namespace: {{ tpl .Values.config.namespace . }}
subjects:
- kind: ServiceAccount
  name: {{ include "arc-cleaner.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "arc-cleaner.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
